name: 'Update Flake Inputs'
description: 'Creates pull requests for each flake input update on Forgejo'
author: 'Your Name'

inputs:
  forgejo-url:
    description: 'forgejo server URL'
    required: true
    default: ${{ forgejo.server_url }}
  forgejo-token:
    description: 'forgejo authentication token'
    required: true
    default: ${{ secrets.forgejo_TOKEN }}
  forgejo-repository:
    description: 'Repository in format owner/repo'
    required: false
    default: ${{ forgejo.repository }}
  exclude-patterns:
    description: 'Comma-separated list of glob patterns to exclude flake.nix files'
    required: false
    default: ''
  base-branch:
    description: 'Base branch to create PRs against'
    required: false
    default: 'main'
  auto-merge:
    description: 'Automatically merge PRs when checks succeed'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for avoiding rate limits when fetching flake inputs'
    required: false
    default: ''
  git-author-name:
    description: 'Git author name for commits'
    required: false
    default: 'forgejo-actions[bot]'
  git-author-email:
    description: 'Git author email for commits'
    required: false
    default: 'forgejo-actions[bot]@noreply.forgejo.io'
  git-committer-name:
    description: 'Git committer name for commits'
    required: false
    default: 'forgejo-actions[bot]'
  git-committer-email:
    description: 'Git committer email for commits'
    required: false
    default: 'forgejo-actions[bot]@noreply.forgejo.io'

runs:
  using: 'composite'
  steps:
    - name: Run update-flake-inputs
      shell: bash
      run: |
        AUTO_MERGE_FLAG=""
        if [[ "${{ inputs.auto-merge }}" == "true" ]]; then
          AUTO_MERGE_FLAG="--auto-merge"
        fi

        # Prepend GitHub access token to NIX_CONFIG if provided
        our_nix_config="extra-experimental-features = nix-command flakes"
        if [[ -n "${{ inputs.github-token }}" ]]; then
          our_nix_config+="
        access-tokens = github.com=${{ inputs.github-token }}"
        fi
        export NIX_CONFIG="${our_nix_config}${NIX_CONFIG:+
        $NIX_CONFIG}"

        set -x

        nix run \
          "${GITHUB_ACTION_PATH}#update-flake-inputs" -- \
          --gitea-url "${{ inputs.forgejo-url }}" \
          --gitea-token "${{ inputs.forgejo-token }}" \
          --gitea-repository "${{ inputs.forgejo-repository }}" \
          --exclude-patterns "${{ inputs.exclude-patterns }}" \
          --base-branch "${{ inputs.base-branch }}" \
          --git-author-name "${{ inputs.git-author-name }}" \
          --git-author-email "${{ inputs.git-author-email }}" \
          --git-committer-name "${{ inputs.git-committer-name }}" \
          --git-committer-email "${{ inputs.git-committer-email }}" \
          $AUTO_MERGE_FLAG
